sudo: required
dist: trusty
language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  api_key:
    secure: L3zdqEpUlwByeuZsgxhM5E18hPGxa9BES7NhviDskbiru2lNfXxhAxHoSMuUOKtdMhhc5eQoqWNQRWlGavLTqQZAa50jI0LWjVWE+7haCV2KpIZKKOW2ItWJitXTtTP08Ta1pvLgTVlDsCsiA/V77wRMF9CR+eex+Hq5eq7eNXCeJBmHA/2BhD9YE7fiRxzvdyFNfO/WF4hnnWXsfihPJQ03OeouD7heaXv6JBJIAxfm8GniIjyHfxghCO0OaTtUDz7ccM2yCtxUiiFArORchbq5AxwgZr2m4qCWamvlW0OM67KioCq+9vP4wxraGFZXdhPk0QCzz6BXNEf1OVNmQOX553jTQuQ8SxdDyx7vSnOkrXxlK2yKWjLvx0HfaiMHq9VZ18HamV+AKxXGZfJfffxyKb3UrySZuS28OXdyVEXxrx6Lc2hn2D/9Ke3ueuJns8GHfmf5E5UgSvgG2fRASd0D8MJM47aHcdDGnw7OQyXRV7eonOK3q4c4gQSDVfoSv6ihlFx4yOjkMtxM+zYJMTzz0iP2TgxaFupetTHACGVJ9j0szzbgkMWPJ8C9AD2BFrpGcQHOkrlBimpkFhbKBCUkxjPpojD9TBd8s3gxAAUZQpulO/1k+fW97ORkhR+PsNCkYf/WhoCYEquqv5qaGbyr4p+9WatT8wvZKfVCGUU=
  on:
    tags: true
    repo: Eyevinn/adxchange-engine
